import type { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export async function up(knex: Knex) {
    return knex.schema
        .createTable(ETableNames.records, (table) => {
            table.uuid("measure_uuid").primary().unique();
            table.string("image").notNullable();
            table.string("customer_code").notNullable();
            table.dateTime("measure_datetime").notNullable();
            table.string("measure_type").notNullable();
            table.boolean("has_confirmed").notNullable().defaultTo(false);
            table.integer("measure_value").notNullable();

            table.comment(
                "Table used to handle and store all the informations generated by the api after analyzing the image"
            );
        })
        .then(() => {
            console.log(`# Create table ${ETableNames.records}`);
        });
}

export async function down(knex: Knex) {
    return knex.schema.dropTable(ETableNames.records).then(() => {
        console.log(`# Dropped table ${ETableNames.records}`);
    });
}
