import type { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export async function up(knex: Knex) {
    return knex.schema
        .createTable(ETableNames.records, (table) => {
            table.bigIncrements("id").primary().index();
            table.string("image");
            table.string("customer_code");
            table.dateTime("measure_time");
            table.enu("measure_type", ["WATER", "GAS"]);
            table.integer("measure_value");
            table.string("measure_uuid").unique();

            table.comment(
                "Table used to handle and store all the informations generated by the api after analyzing the image"
            );
        })
        .then(() => {
            console.log(`# Create table ${ETableNames.records}`);
        });
}

export async function down(knex: Knex) {
    return knex.schema.dropTable(ETableNames.records).then(() => {
        console.log(`# Dropped table ${ETableNames.records}`);
    });
}
