# Etapa 1: Build
FROM node:20-alpine AS build

# Definir diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar arquivos de dependências para o contêiner
COPY . .

# Instalar dependências
RUN yarn install

# Realizar o build do projeto
RUN yarn tsc

# Expor a porta da aplicação
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["yarn", "start"]